/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A2.Proyecto.Formularios.Registros;

import A2.Proyecto.Controladores.CambiostockJpaController;
import A2.Proyecto.Controladores.ProductoJpaController;
import A2.Proyecto.Entidades.Cambiostock;
import A2.Proyecto.Entidades.Producto;
import java.util.Date;
import javax.swing.JOptionPane;
 

/**
 *
 * @author WELLINGTON
 */
public class RegistrarCompra extends javax.swing.JFrame {
    
    
    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarCompra() {
        initComponents();
        limpiar();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cprodtxt = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        apellidotxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomprodtxt = new javax.swing.JTextField();
        canttxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        provtxt = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        marctxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Codigo Producto");

        cprodtxt.setText("jTextField1");
        cprodtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cprodtxtKeyTyped(evt);
            }
        });

        registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cerrar.setText("CERRAR");
        cerrar.setAlignmentX(1.0F);
        cerrar.setAlignmentY(1.0F);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("COMPRAS");

        apellidotxt.setText("Nombre Producto");

        jLabel7.setText("Cantidad");

        nomprodtxt.setText("jTextField2");
        nomprodtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomprodtxtKeyTyped(evt);
            }
        });

        canttxt.setText("jTextField4");
        canttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                canttxtKeyTyped(evt);
            }
        });

        jLabel3.setText("Proveedor");

        provtxt.setText("jTextField1");

        buscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        marctxt.setText("jTextField1");

        jLabel2.setText("Marca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(apellidotxt)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marctxt)
                            .addComponent(provtxt)
                            .addComponent(cprodtxt)
                            .addComponent(nomprodtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrar)
                .addGap(36, 36, 36)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cprodtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomprodtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(buscar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        LlamarFormularios.llamarAdmin();
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void cprodtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cprodtxtKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'Z') && (c<' ' || c>' ') && (c<'ñ' || c>'ñ') && (c<'Ñ' || c>'Ñ')) evt.consume();
    }//GEN-LAST:event_cprodtxtKeyTyped

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        
        if ((canttxt.getText().equals(""))) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe Ingresar una cantidad \n", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //coloca el cursor en el campo en blanco
            if (canttxt.getText().equals("")) {
                canttxt.requestFocus();
            }

        } else {
            try {
                //accion de insertar datos en la base de datos  
                Cambiostock cambiostock = new Cambiostock();
                CambiostockJpaController CCambiostock = new CambiostockJpaController();

                int ultimo = CCambiostock.getCambiostockCount();
                //System.out.println(ultimo);
                cambiostock.setCodigo(ultimo + 1);
                cambiostock.setCodigoProducto(cprodtxt.getText());
                cambiostock.setCantidad(Integer.parseInt(canttxt.getText()));
                cambiostock.setTipo("Compra");
                
                cambiostock.setFecha(fechasis());
                
                CCambiostock.create(cambiostock);
                javax.swing.JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO\n", "COMPRAS", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                ///////////////////////////////////////////////////////////////////////
                //////////////////////////////////////////////////////////////////////
                ProductoJpaController CProducto = new ProductoJpaController();
                Producto producto = CProducto.findProducto(cprodtxt.getText());
                
                int cantidadAux=producto.getCantidad()+Integer.parseInt(canttxt.getText());
                producto.setCantidad(cantidadAux);
                
                CProducto.edit(producto);
                
                limpiar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
        
    }//GEN-LAST:event_registrarActionPerformed

    private void nomprodtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomprodtxtKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'Z') && (c<' ' || c>' ') && (c<'ñ' || c>'ñ') && (c<'Ñ' || c>'Ñ')) evt.consume();
    }//GEN-LAST:event_nomprodtxtKeyTyped

    private void canttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canttxtKeyTyped
        char c = evt.getKeyChar();
        if ((c<'0'|| c>'9')) evt.consume();
        
        if(canttxt.getText().length()==8){
            evt.consume();
        }
    }//GEN-LAST:event_canttxtKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if ((cprodtxt.getText().equals(""))) {

            javax.swing.JOptionPane.showMessageDialog(this, "INGRESE UN CODIGO \n", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //coloca el cursor en el campo en blanco
            if (cprodtxt.getText().equals("")) {
                cprodtxt.requestFocus();
            }
        } else {
            try {

                ProductoJpaController CProducto = new ProductoJpaController();
                Producto producto = CProducto.findProducto(cprodtxt.getText());

                desbloquear();
                nomprodtxt.setText(producto.getNombre());
                provtxt.setText(producto.getProveedor());
                marctxt.setText(producto.getMarca());
                bloquear();
                desbloquear2();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidotxt;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField canttxt;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField cprodtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField marctxt;
    private javax.swing.JTextField nomprodtxt;
    private javax.swing.JTextField provtxt;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

private void limpiar() {                                          

        cprodtxt.setText("");
        nomprodtxt.setText("");
        provtxt.setText("");
        canttxt.setText("");
        marctxt.setText("");
     
        cprodtxt.requestFocus();      
}

private void bloquear() { 
    
        nomprodtxt.setEnabled(false);
        provtxt.setEnabled(false);
        canttxt.setEnabled(false);
        marctxt.setEnabled(false);
        
        registrar.setEnabled(false);
      
}

private void desbloquear() { 
    
        nomprodtxt.setEnabled(true);
        provtxt.setEnabled(true);
        canttxt.setEnabled(true);
        marctxt.setEnabled(true);
        
        registrar.setEnabled(true);
      
}

private void desbloquear2() { 
   
        canttxt.setEnabled(true);
        
        registrar.setEnabled(true);
        canttxt.requestFocus();
}

public Date fechasis() {
    java.util.Date date = new Date();
    java.sql.Date fechaActual = new java.sql.Date(date.getTime());

    return (fechaActual);
}

}
