/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S1.Proyecto.Formularios.Registros;

import S1.Proyecto.Controladores.UsuarioJpaController;
import S1.Proyecto.Entidades.Usuario;
import S1.Proyecto.FuncionesAuxiliares.CodificarContraseña;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
 

/**
 *
 * @author WELLINGTON
 */
public class Login extends javax.swing.JFrame {
    
    
    /**
     * Creates new form RegistrarUsuario
     */
    public Login() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ustxt = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        apellidotxt = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(350, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        ustxt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ustxt.setText("jTextField1");
        ustxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ustxtKeyTyped(evt);
            }
        });

        entrar.setBackground(new java.awt.Color(0, 154, 154));
        entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Ingresar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        cerrar.setBackground(new java.awt.Color(229, 88, 100));
        cerrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("Salir");
        cerrar.setAlignmentX(1.0F);
        cerrar.setAlignmentY(1.0F);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 35)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Iniciar sesión");

        apellidotxt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        apellidotxt.setForeground(new java.awt.Color(255, 255, 255));
        apellidotxt.setText("Contraseña");

        passtxt.setFont(new java.awt.Font("Calibri Light", 0, 15)); // NOI18N
        passtxt.setText("jPasswordField1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenavatar_u7.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(43, 61, 83));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(apellidotxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(ustxt))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(92, 92, 92))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 145, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 145, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 200, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void ustxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ustxtKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'0'||c>'9')) evt.consume();
    }//GEN-LAST:event_ustxtKeyTyped

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // se verifica que todos los campos esten llenos
        if((ustxt.getText().equals("")) || (passtxt.getText().equals(""))){
                
                javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                //coloca el cursor en el campo en blanco
                if(passtxt.getText().equals("")){passtxt.requestFocus();}
                if(ustxt.getText().equals("")){ustxt.requestFocus();}
            }
            else{
                try {
                    //se busca el usuario ingresado para poder realizar
                    //la autenticacion
                    UsuarioJpaController CUsuario = new UsuarioJpaController();
                    Usuario usuario = CUsuario.findUsuario(ustxt.getText());
                    
                    String passTemporal=CodificarContraseña.sha1(passtxt.getText());
                    //se verifica que la contraseña ingresada sea la correcta
                    if(passTemporal.equals(usuario.getPass())){
                        //si el usuario ingresa por primera vez al sistema
                        //este le solicita que actualice la contraseña generada
                        //por el sistema, a una ingresada por el usuario
                        if(usuario.getNuevoUsuario()==1){
                            JOptionPane.showMessageDialog(null, "DEBE ACUALIZAR SU CONTRASEÑA \n","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                            //se invoca al formulario de cambio de contraseña
                            LlamarFormularios.llamarCambioContraseña();
                            //se enviaa el nombre de usuario al form de cambio de contraseña
                            CambioContraseña.lus.setText(ustxt.getText());
                            dispose();
                        }else{
                            
                            //si no es la primera vez que el usuario ingresa
                            //se procede a verificar si el usuario tiene
                            //privilegios de administrador, o no
                            //y se muestra el form correspondiente
                            if(usuario.getTipo()==0){
                             //System.out.println(usuario.getPass());
                            LlamarFormularios.llamarInvitado();
                            dispose();
                            }

                            if(usuario.getTipo()==1){
                                //System.out.println(usuario.getPass());
                                LlamarFormularios.llamarAdmin();
                                dispose();
                            }
                        }  
                    }else{
                        
                        //si la contraseña no es correcta se muestra la alerta
                        JOptionPane.showMessageDialog(null, "CONTRASEÑA INCORRECTA \n"+"           Vuelva a Intentarlo \n","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                        passtxt.setText("");
                        passtxt.requestFocus();
                    }
                        
                        
                        

                } catch (Exception e){
                    //si el usuario no es correcto, o no existe se muestra la alerta
                    JOptionPane.showMessageDialog(null, "USUARIO INCORRECTO \n"+"      Vuelva a Intentarlo","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                    limpiar();
                }
            
            }
        
    }//GEN-LAST:event_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidotxt;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JTextField ustxt;
    // End of variables declaration//GEN-END:variables

    //metodo para limpiar los campos
private void limpiar() {                                          
        ustxt.setText("");
        passtxt.setText("");
        
        ustxt.requestFocus();      
}

}
